#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH

DRUSH=${OPENSHIFT_REPO_DIR}vendor/bin/drush
DRUPAL_SITE_DIR=${OPENSHIFT_REPO_DIR}sites
DRUPAL_PRIVATE_DIR=${OPENSHIFT_REPO_DIR}sites/default/files/private
DRUPAL_SETTINGS=${DRUPAL_SITE_DIR}/default/settings.php
DRUPAL_LOCAL_SETTINGS=${DRUPAL_SITE_DIR}/default/local.settings.php
# Set the initial password
admin_pwd=$(generate_password)

for f in ${DRUPAL_SITE_DIR}/*/;
  do
    dir=${dir%*/}
    dir=${dir##*/}
done;